---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-yaml
      - id: sort-simple-yaml

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-imports
      - id: go-fmt
      - id: golangci-lint
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: go-build

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.19.0
    hooks:
      - id: check-git-config-email
        args: ["--domains", "aerlingus.com"]
