---
name: Update modules

on:
  workflow_dispatch:

jobs:
  update-modules:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          show-progress: "false"
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
          cache: true
      - run: go telemetry off
      - run: go get -u=patch
      - run: go mod tidy
      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
            go build -trimpath -buildvcs=false \
              -buildmode=exe \
              -ldflags "-s -w" \
              -tags 'static_build' \
              -o bootstrap
      - run: go test -v ./...
      - run: git --no-pager config user.email 'update-modules@github.com'
      - run: git --no-pager config user.name 'Update Modules'
      - run: git checkout -b fix/${{ github.run_number }}
      - run: |
          git commit --all --message 'fix: Bump modules - ${{ github.run_number }}'
      - run: git --no-pager push --set-upstream origin $(git --no-pager branch --no-color --show-current)
      - run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ github.token }}
